# Generated by Django 4.0.4 on 2022-06-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_username_profile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
