# Generated by Django 4.0.4 on 2022-06-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='docs_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
