# Generated by Django 4.0.5 on 2022-06-21 03:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_name_profile_full_name_remove_profile_surname'),
        ('projects', '0009_review_owner_alter_review_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('date', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
