# Generated by Django 4.0.5 on 2022-06-21 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_name_profile_full_name_remove_profile_surname'),
        ('projects', '0012_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('project', 'buyer')},
        ),
    ]
