# Generated by Django 4.0.5 on 2022-06-21 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-total_votes', '-scores_votes']},
        ),
    ]
